language: node_js
node_js:
    - '14'
script:
    - npm run build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: ./public
    repo: MichaelDuo/michaelduo.github.io
    target-branch: master
    on:
        branch: master
